[package]
name = "opa-util-proc-macros-core"
version.workspace = true
authors.workspace = true
edition.workspace = true

[dependencies]
proc-macro2.workspace = true
proc-macro-util.workspace = true
quote.workspace = true
syn.workspace = true
