[package]
name = "authzen-examples"
version = "0.1.0"
edition = "2021"
authors = ["Trey Lowerison"]

[dependencies]
anyhow = "1"
authzen = { path = "../authzen", features = ["diesel-postgres"] }
chrono = { version = "0.4", features = ["serde"] }
diesel = { version = "2", features = ["extras", "numeric", "postgres"] }
diesel-async = { version = "0.2", features = ["postgres"] }
diesel-util = { git = "https://github.com/tlowerison/diesel-util", rev = "bfd6354", features = ["postgres"] }
serde = { version = "1", features = ["derive"] }
uuid = { version = "1", features = ["serde" ]}
