[package]
name = "authzen-examples"
version = "0.1.0"
edition = "2021"
authors = ["Trey Lowerison"]

[dependencies]
anyhow = "1"
async-trait = "0"
authzen = { path = "../authzen", features = ["diesel-postgres", "extra-traits", "opa-decision-maker"] }
chrono = { version = "0.4", features = ["serde"] }
derive_more = "0"
diesel = { version = "2", features = ["extras", "numeric", "postgres"] }
diesel-async = { version = "0.2", features = ["postgres"] }
diesel-util = { git = "https://github.com/tlowerison/diesel-util", rev = "bc7d164", features = ["postgres"] }
opa-util = { path = "/Users/tlowerison/code/opa-util/opa-util" }
serde = { version = "1", features = ["derive"] }
service-util = { git = "https://github.com/tlowerison/service-util", rev = "5cc73b5", features = ["db"] }
typed-builder = "0.11.0"
uuid = { version = "1", features = ["serde", "v4"] }
