[package]
name = "authzen-diesel-proc-macros"
version.workspace = true
authors.workspace = true
edition.workspace = true
build = "../../../build.rs"

[dependencies]
core = { path = "core", package = "authzen-diesel-proc-macros-core" }
proc-macro2.workspace = true
syn.workspace = true

[build-dependencies]
rustc_version.workspace = true

[lib]
proc-macro = true
