[package]
name = "opa-util-proc-macros"
version.workspace = true
authors.workspace = true
edition.workspace = true

[dependencies]
core = { path = "core", package = "opa-util-proc-macros-core" }
proc-macro-util.workspace = true

[lib]
proc-macro = true
