[package]
name = "authzen-opa-proc-macros-core"
version.workspace = true
authors.workspace = true
edition.workspace = true
build = "../../../../build.rs"

[dependencies]
proc-macro2.workspace = true
proc-macro-util.workspace = true
quote.workspace = true
syn.workspace = true

[build-dependencies]
rustc_version.workspace = true
