name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name:
      run: cargo doc --verbose

    - name: Upload a Build Artifact
      uses: actions/upload-artifact@v3.1.2
      with:
        name: artifact # default
        path: target/doc/authzen/**

    - name: Deploy GitHub Pages site
      uses: actions/deploy-pages@v1.2.4
      with:
        artifact_name: github-pages # default
        # timeout: # default is 600000
        # error_count: # Maximum number of status report errors before cancelling a deployment (default: 10)
        # reporting_interval: # Time in milliseconds between two deployment status report (default: 5000)
