name: Rust

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

env:
  CARGO_TERM_COLOR: always

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: write
  pages: write
  id-token: write

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Install nightly rust toolchain
      run: rustup toolchain install nightly

    - name: Build docs
      run: cargo +nightly doc --workspace --no-deps --verbose --color always

    - name: Create html redirect to correct doc subdirectory
      run: 'echo "<meta http-equiv=\"refresh\" content=\"0; url=authzen\">" > target/doc/index.html'

    - name: Upload a Build Artifact
      uses: actions/upload-artifact@v3.1.2
      with:
        name: github-pages
        path: target/doc/**

    - name: Deploy GitHub Pages site
      uses: actions/deploy-pages@v1.2.4
      with:
        artifact_name: github-pages
        # timeout: # default is 600000
        # error_count: # Maximum number of status report errors before cancelling a deployment (default: 10)
        # reporting_interval: # Time in milliseconds between two deployment status report (default: 5000)
