name: Rust

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

env:
  CARGO_TERM_COLOR: always

# Allow one concurrent deployment
concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  checkout:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

  setup:
    needs: checkout
    runs-on: ubuntu-latest
    steps:
    - id: ruby-env
      run: echo ::set-output docs_dir="$GITHUB_WORKSPACE/docs"

    - name: Setup Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: "3.1.3" # Not needed with a .ruby-version file
        bundler-cache: true # runs "bundle install" and caches installed gems automatically
        cache-version: 0 # Increment this number if you need to re-download cached gems
        working-directory: ${{ steps.ruby-env.outputs.docs_dir }}

    - name: Install nightly rust toolchain
      run: rustup toolchain install nightly

    - name: Setup Pages
      uses: actions/configure-pages@v3

  build:
    needs: setup
    runs-on: ubuntu-latest
    steps:
    - name: Build docs
      run: cargo +nightly doc --workspace --no-deps --verbose --color always

    - name: Create html redirect to correct doc subdirectory
      run: echo "<meta http-equiv=\"refresh\" content=\"0; url=authzen\">" > target/doc/index.html

    - name: Move generated docs to docs directory
      run: find target/doc -mindepth 1 -maxdepth 1 | sed "s:target/doc/::g" | xargs -n 1 -I {} sh -c "mv target/doc/{} docs/{}"

    - name: Build with Jekyll
      # Outputs to the ./_site directory by default
      run: bundle exec jekyll build
      env:
        JEKYLL_ENV: production

    - name: Upload a Build Artifact
      uses: actions/upload-artifact@v3
      with:
        name: github-pages
        path: docs/**

  deploy:
    needs: build
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
      pages: write
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
    - name: Deploy GitHub Pages site
      uses: actions/deploy-pages@v1
      with:
        artifact_name: github-pages
        # timeout: # default is 600000
        # error_count: # Maximum number of status report errors before cancelling a deployment (default: 10)
        # reporting_interval: # Time in milliseconds between two deployment status report (default: 5000)
